application: thermal-highway-510
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

# a static directory mapping
- url: /js
  static_dir: js

# a static directory mapping
- url: /css
  static_dir: css

- url: /
  static_files: template/login.html
  upload: template/login\.html

- url: /event/.*
  script: event.app
  login: required

- url: /home.*
  script: home.app
  login: required
  
- url: /comments/.*
  script: comment.app
  login: required

- url: /report/.*
  script: report.app
  login: required

- url: /images
  static_dir: images

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
